# Dream.OS RAG Configuration
# Configuration for retrieval-augmented generation system

# Embedding Configuration
embeddings:
  model: "all-MiniLM-L6-v2"  # Local model by default
  # Alternative: "text-embedding-3-large" for OpenAI embeddings
  dimension: 384  # Will be auto-detected
  normalize: true
  batch_size: 32

# Chunking Configuration
chunking:
  max_chunk_size: 512
  overlap_size: 50
  min_chunk_size: 100
  preserve_sentences: true
  preserve_paragraphs: true
  strategy: "adaptive"  # adaptive, sentence, paragraph, sliding_window

# Database Configuration
database:
  path: "dreamos/memory_layers/long_term.sqlite"
  table_name: "rag"
  create_indexes: true
  vacuum_after_insert: false

# Retrieval Configuration
retrieval:
  top_k: 8
  similarity_threshold: 0.7
  max_context_length: 2048
  rerank: false
  rerank_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"

# Memory Layers
memory_layers:
  short_term:
    path: "dreamos/memory_layers/short_term.json"
    max_entries: 100
    ttl_seconds: 3600  # 1 hour
    
  medium_term:
    path: "dreamos/memory_layers/medium_term.json"
    max_entries: 1000
    ttl_seconds: 86400  # 24 hours
    
  long_term:
    path: "dreamos/memory_layers/long_term.sqlite"
    max_entries: -1  # Unlimited
    backup_frequency: 86400  # Daily backup

# Performance Configuration
performance:
  enable_caching: true
  cache_size: 1000
  batch_processing: true
  parallel_workers: 4
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/rag.log"
  max_size_mb: 100
  backup_count: 5

# Export Configuration
export:
  formats: ["jsonl", "npz", "json"]
  compress: true
  include_embeddings: true
  include_metadata: true