# DreamVault Configuration

# Rate limiting configuration - Based on ChatGPT API limits
rate_limits:
  global:
    requests_per_minute: 0.83  # ~50 messages per hour (conservative)
    burst_size: 5
  per_host:
    requests_per_minute: 0.28  # ~17 messages per hour (conservative)
    burst_size: 3
  # ChatGPT-specific limits
  chatgpt:
    gpt4o:
      messages_per_3hrs: 150
      burst_size: 10
    gpt4o_mini:
      auto_throttle: true
      fallback_to: "gpt4o"
    gpt45:
      messages_per_week: 50
      burst_size: 5
    o3_mini_high:
      messages_per_day: 50
      burst_size: 3

# Batch processing configuration
batch:
  max_conversations: 100
  batch_size: 10
  retry_attempts: 3
  retry_delay: 5

# File paths and directories
paths:
  raw_data: "data/raw"
  summaries: "data/summary"
  indexes: "data/index"
  runtime: "runtime"
  metrics: "ops/metrics"

# LLM configuration for summarization
llm:
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.1

# Embedding configuration
embedding:
  model: "text-embedding-ada-002"
  embedding_dim: 1536
  batch_size: 100

# PII redaction configuration
redaction:
  patterns:
    - pattern: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"
      type: "email"
    - pattern: "\\b\\d{3}-\\d{3}-\\d{4}\\b"
      type: "phone"
    - pattern: "\\b\\d{4}-\\d{4}-\\d{4}-\\d{4}\\b"
      type: "credit_card"
    - pattern: "\\b\\d{3}-\\d{2}-\\d{4}\\b"
      type: "ssn"
    - pattern: "\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b"
      type: "ip_address"
  replacements:
    email: "[EMAIL]"
    phone: "[PHONE]"
    credit_card: "[CREDIT_CARD]"
    ssn: "[SSN]"
    ip_address: "[IP_ADDRESS]"

# Processing options
processing:
  enable_redaction: true
  enable_summarization: true
  enable_embeddings: true
  enable_indexing: true
  validate_summaries: true
  save_raw_data: false

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: true
  max_file_size: "10MB"
  backup_count: 5 